export const GET_ALL_COURSES_REQUEST = 'GET_ALL_COURSES_REQUEST';
export const GET_ALL_COURSES_SUCCESS = 'GET_ALL_COURSES_SUCCESS';
export const GET_ALL_COURSES_FAILURE = 'GET_ALL_COURSES_FAILURE';

export const GET_COURSE_BY_ID_REQUEST = 'GET_COURSE_BY_ID_REQUEST';
export const GET_COURSE_BY_ID_SUCCESS = 'GET_COURSE_BY_ID_SUCCESS';
export const GET_COURSE_BY_ID_FAILURE = 'GET_COURSE_BY_ID_FAILURE';

export const ENROLL_COURSE_REQUEST = 'ENROLL_COURSE_REQUEST';
export const ENROLL_COURSE_SUCCESS = 'ENROLL_COURSE_SUCCESS';
export const ENROLL_COURSE_FAILURE = 'ENROLL_COURSE_FAILURE';

export const LEAVE_COURSE_REQUEST = 'LEAVE_COURSE_REQUEST';
export const LEAVE_COURSE_SUCCESS = 'LEAVE_COURSE_SUCCESS';
export const LEAVE_COURSE_FAILURE = 'LEAVE_COURSE_FAILURE';

export const CREATE_COURSE_REQUEST = 'CREATE_COURSE_REQUEST';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_FAILURE = 'CREATE_COURSE_FAILURE';

export const UPDATE_COURSE_REQUEST = 'UPDATE_COURSE_REQUEST';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const UPDATE_COURSE_FAILURE = 'UPDATE_COURSE_FAILURE';

export const GET_LECTURER_COURSES_REQUEST = 'GET_LECTURER_COURSES_REQUEST';
export const GET_LECTURER_COURSES_SUCCESS = 'GET_LECTURER_COURSES_SUCCESS';
export const GET_LECTURER_COURSES_FAILURE = 'GET_LECTURER_COURSES_FAILURE';

export const GET_LISTENER_COURSES_REQUEST = 'GET_LISTENER_COURSES_REQUEST';
export const GET_LISTENER_COURSES_SUCCESS = 'GET_LISTENER_COURSES_SUCCESS';
export const GET_LISTENER_COURSES_FAILURE = 'GET_LISTENER_COURSES_FAILURE';
